# Generated by Django 3.0.3 on 2020-04-01 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_freelancerchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerchat',
            name='sort_str',
        ),
        migrations.AddField(
            model_name='freelancerchat',
            name='room_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='OnGoingProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer_set', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
